# permissions for end users to view boxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: box-viewer-role
rules:
- apiGroups:
  - foo.my.domain
  resources:
  - boxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - foo.my.domain
  resources:
  - boxes/status
  verbs:
  - get
