# permissions for end users to view boxrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boxrecord-viewer-role
rules:
- apiGroups:
  - foo.my.domain
  resources:
  - boxrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - foo.my.domain
  resources:
  - boxrecords/status
  verbs:
  - get
